<?php

namespace AppBundle\Repository;

/**
 * authors_nameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class authors_nameRepository extends \Doctrine\ORM\EntityRepository
{
}
