<?php

namespace AppBundle\Repository;

/**
 * authorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class authorsRepository extends \Doctrine\ORM\EntityRepository
{
}
