<?php

namespace AppBundle\Repository;

/**
 * books_nameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class books_nameRepository extends \Doctrine\ORM\EntityRepository
{
}
