<?php

namespace AppBundle\Repository;

/**
 * booksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class booksRepository extends \Doctrine\ORM\EntityRepository
{
}
