<?php

namespace AppBundle\Repository;

/**
 * citiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class citiesRepository extends \Doctrine\ORM\EntityRepository
{
}
