<?php

namespace AppBundle\Repository;

/**
 * cities_nameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cities_nameRepository extends \Doctrine\ORM\EntityRepository
{
}
