<?php

namespace AppBundle\Repository;

/**
 * entitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
