<?php

namespace AppBundle\Repository;

/**
 * erasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class erasRepository extends \Doctrine\ORM\EntityRepository
{
}
