<?php

namespace AppBundle\Repository;

/**
 * eras_nameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eras_nameRepository extends \Doctrine\ORM\EntityRepository
{
}
