<?php

namespace AppBundle\Repository;

/**
 * genre_nameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class genre_nameRepository extends \Doctrine\ORM\EntityRepository
{
}
