<?php

namespace AppBundle\Repository;

/**
 * genreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class genreRepository extends \Doctrine\ORM\EntityRepository
{
}
