<?php

namespace AppBundle\Repository;

/**
 * keywords_type_nameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class keywords_type_nameRepository extends \Doctrine\ORM\EntityRepository
{
}
