<?php

namespace AppBundle\Repository;

/**
 * keywords_familliesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class keywords_familliesRepository extends \Doctrine\ORM\EntityRepository
{
}
