<?php

namespace AppBundle\Repository;

/**
 * keywordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class keywordsRepository extends \Doctrine\ORM\EntityRepository
{
}
