<?php

namespace AppBundle\Repository;

/**
 * langsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class langsRepository extends \Doctrine\ORM\EntityRepository
{
}
