<?php

namespace AppBundle\Repository;

/**
 * manuscripts_translationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class manuscripts_translationsRepository extends \Doctrine\ORM\EntityRepository
{
}
