<?php

namespace AppBundle\Repository;

/**
 * manuscriptsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class manuscriptsRepository extends \Doctrine\ORM\EntityRepository
{
}
