<?php

namespace AppBundle\Repository;

/**
 * motifsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class motifsRepository extends \Doctrine\ORM\EntityRepository
{
}
