<?php

namespace AppBundle\Repository;

/**
 * notesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notesRepository extends \Doctrine\ORM\EntityRepository
{
}
