<?php

namespace AppBundle\Repository;

/**
 * notes_translationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notes_translationsRepository extends \Doctrine\ORM\EntityRepository
{
}
