<?php

namespace AppBundle\Repository;

/**
 * scholiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class scholiesRepository extends \Doctrine\ORM\EntityRepository
{
}
