<?php

namespace AppBundle\Repository;

/**
 * scholies_translationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class scholies_translationsRepository extends \Doctrine\ORM\EntityRepository
{
}
