<?php

namespace AppBundle\Repository;

/**
 * texts_vocalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class texts_vocalsRepository extends \Doctrine\ORM\EntityRepository
{
}
