<?php

namespace AppBundle\Repository;

/**
 * texts_translationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class texts_translationsRepository extends \Doctrine\ORM\EntityRepository
{
}
