<?php

namespace AppBundle\Repository;

/**
 * textsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class textsRepository extends \Doctrine\ORM\EntityRepository
{
}
