<?php

namespace AppBundle\Repository;

/**
 * translationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class translationsRepository extends \Doctrine\ORM\EntityRepository
{
}
