<?php

namespace AppBundle\Repository;

/**
 * URI_sourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class URI_sourceRepository extends \Doctrine\ORM\EntityRepository
{
}
