<?php

namespace AppBundle\Repository;

/**
 * URI_type_nameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class URI_type_nameRepository extends \Doctrine\ORM\EntityRepository
{
}
