<?php

namespace AppBundle\Repository;

/**
 * URIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class URIRepository extends \Doctrine\ORM\EntityRepository
{
}
