api_authors:
    type: rest
    resource: AppBundle\Controller\Api\AuthorsController
    prefix: /v1
    name_prefix: api_v1_

api_books:
    type: rest
    resource: AppBundle\Controller\Api\BooksController
    prefix: /v1
    name_prefix: api_v1_

api_cities:
    type: rest
    resource: AppBundle\Controller\Api\CitiesController
    prefix: /v1
    name_prefix: api_v1_

api_entities:
    type: rest
    resource: AppBundle\Controller\Api\EntitiesController
    prefix: /v1
    name_prefix: api_v1_

api_eras:
    type: rest
    resource: AppBundle\Controller\Api\ErasController
    prefix: /v1
    name_prefix: api_v1_

api_genres:
    type: rest
    resource: AppBundle\Controller\Api\GenresController
    prefix: /v1
    name_prefix: api_v1_

api_keywords:
    type: rest
    ressource: AppBundle\Controller\Api\KeywordsController
    prefix: /v1
    name_prefix: api_v1_

api_keywords_categories:
    type: rest
    ressource: AppBundle\Controller\Api\KeywordsCategoriesController
    prefix: /v1
    name_prefix: api_v1_

api_keywords_families:
    type: rest
    ressource: AppBundle\Controller\Api\KeywordsFamiliesController
    prefix: /v1
    name_prefix: api_v1_

api_manuscript:
    type: rest
    ressource: AppBundle\Controller\Api\ManuscriptController
    prefix: /v1
    name_prefix: api_v1_

api_motifs:
    type: rest
    ressource: AppBundle\Controller\Api\MotifsController
    prefix: /v1
    name_prefix: api_v1_

api_notes:
    type: rest
    ressource: AppBundle\Controller\Api\NotesController
    prefix: /v1
    name_prefix: api_v1_

api_scholies:
    type: rest
    ressource: AppBundle\Controller\Api\ScholiesController
    prefix: /v1
    name_prefix: api_v1_

api_texts:
    type: rest
    ressource: AppBundle\Controller\Api\TextsController
    prefix: /v1
    name_prefix: api_v1_

api_uri_categories:
    type: rest
    ressource: AppBundle\Controller\Api\UriCategoriesController
    prefix: /v1
    name_prefix: api_v1_

api_uri:
    type: rest
    ressource: AppBundle\Controller\Api\UriController
    prefix: /v1
    name_prefix: api_v1_
    
api_uri_source:
    type: rest
    ressource: AppBundle\Controller\Api\UriSourceController
    prefix: /v1
    name_prefix: api_v1_