<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangRepository extends EntityRepository
{
}
