#Front
app:
    resource: "@AppBundle/Controller/Front/"
    type:     annotation

#Backend
app_back_end:
    resource: "@AppBundle/Controller/Back/"
    type:     annotation
    prefix:   /admin/

#Api
app_api:
    type: rest
    resource: "@AppBundle/Resources/config/routing-api.yml"
    prefix:   /api

# Doc
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

# FOSAuthServerBundle
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"