easy_admin:
    entities:
        AuthorsTranslations:
            class: AppBundle\Entity\AuthorsTranslations
            label: 'Authors Translations'
            list:
                fields: ['id', 'name', 'about']
                title: "All the authors translations"
            form:
                fields:
                    - { property: 'name', type: 'text', label: 'Name' }
                    - { property: 'about', type: 'textarea', label: 'About' }
                    - { property: 'language', label: 'Language' }
                    - { property: 'author', type: 'easyadmin_autocomplete', label: 'Author ID' }