easy_admin:
    entities:
        BooksTranslations:
            class: AppBundle\Entity\BooksTranslations
            label: 'Books translations'
            list:
                fields: ['id', 'name']
                title: "All the Books translations"
            form:
                fields:
                    - { property: 'name', label: 'Book name' }
                    - { property: 'language', label: 'Language' }
                    - { property: 'book', type: 'easyadmin_autocomplete', label: 'Book ID' }
