easy_admin:
    entities:
        Books:
            class: AppBundle\Entity\Books
            label: 'Books'
            list:
                fields: ['id', 'bookTranslations']
                title: "All the Books"
            form:
              fields:
                  - { property: 'bookTranslations', label: 'Book translations' }