easy_admin:
    entities:
        EntitiesTranslations:
            class: AppBundle\Entity\EntitiesTranslations
            label: 'Entities translations'
            list:
                fields: ['id', 'textTranslated']
                title: "All the Entities translations"
            form:
                fields:
                    - { property: 'entity', type: 'easyadmin_autocomplete', label: 'Entity ID' }
                    - { property: 'language', type: 'easyadmin_autocomplete', label: 'Language ID' }
                    - { property: 'language', label: 'Language' }
                    - { property: 'textTranslated', type: 'textarea', label: 'Tanslation of the text' }
