easy_admin:
    entities:
        ErasTranslations:
            class: AppBundle\Entity\ErasTranslations
            label: 'Eras translations'
            list:
                fields: ['id', 'era', 'name']
                title: "All the Eras translations"
            form:
                fields:
                    - { property: 'name', type: 'text', label: 'Name' }
                    - { property: 'cultureCenters', type: 'textarea', label: 'Culture Centers' }
                    - { property: 'description', type: 'textarea', label: 'Description' }
                    - { property: 'language', label: 'Language' }
                    - { property: 'era', label: 'Era ID' }