easy_admin:
    entities:
        Eras:
            class: AppBundle\Entity\Eras
            label: 'Eras'
            list:
                fields: ['id', 'dateBegin', 'dateEnd', 'eraTranslations']
                title: "All the Eras"
            form:
                fields:
                    - { property: 'dateBegin', type: 'integer', label: 'Date of beginning' }
                    - { property: 'dateEnd', type: 'integer', label: 'Date of ending' }
                    - { property: 'eraTranslations', label: 'Era translations' }