easy_admin:
    entities:
        Genres:
            class: AppBundle\Entity\Genres
            label: 'Genres'
            list:
                fields: ['id', 'genreTranslations']
                title: "All the Genres"
            form:
                fields:
                    - { property: 'genreTranslations', label: 'Genre translations' }