easy_admin:
    entities:
        Group:
            class: AppBundle\Entity\Group
            label: 'Group'
            list:
                fields: ['id', 'name']
                title: "All the Groups"
            form:
                fields:
                    - { property: 'name', type: 'text', label: 'Name' }
                    - { property: 'roles', label: 'Roles' }