easy_admin:
    entities:
        KeywordsCategories:
            class: AppBundle\Entity\KeywordsCategories
            label: 'Keywords categories'
            list:
                fields: ['id', 'keywords']
                title: "All the Keywords categories"

            form:
                fields:
                    - { property: 'keywords', label: 'Keyword ID' }
