easy_admin:
    entities:
        KeywordsTranslations:
            class: AppBundle\Entity\KeywordsTranslations
            label: 'Keywords translations'
            list:
                fields: ['id', 'keyword', 'title']
                title: "All the Keywords translations"

            form:
                fields:
                    - { property: 'title', type: 'text', label: 'Title' }
                    - { property: 'description', type: 'textarea', label: 'Description' }
                    - { property: 'language', label: 'Language' }
                    - { property: 'keyword', label: 'Keyword ID' }
